return {
  TSelect =     { 'Pmenu', true },
  TVisible =    { 'Special', true },
  THidden =     { 'Comment', true },
  TExtra =      { 'guifg=#87af87 guibg=#444444', false },
  TSpecial =    { 'PmenuSel', true },
  TFill =       { 'Folded', true },
  TNumSel =     { 'cterm=bold gui=bold guifg=#87875f guibg=#363636', false },
  TNum =        { 'guifg=#87875f guibg=#363636', false },
  TCorner =     { 'Special', true },
  TSelectMod =  { 'cterm=bold gui=bold guifg=#af0000 guibg=#444444', false },
  TVisibleMod = { 'cterm=bold gui=bold guifg=#af0000', false },
  THiddenMod =  { 'cterm=bold gui=bold guifg=#af0000', false },
  TExtraMod =   { 'cterm=bold gui=bold guifg=#af0000', false },
  normalbg =    '262626',
  dimfg =       '6c6c6c',
}
